[1m========================================================= test session starts =========================================================
platform darwin -- Python 3.12.8, pytest-8.0.2, pluggy-1.5.0 -- /opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/python3.12
cachedir: .pytest_cache
rootdir: /Users/zhijuanzhang/Documents/UdacityCourse/MLOps_P2_Reproducible_Pipeline/Exercise/lesson-3-data-validation/exercises/exercise_9/starter
[1mcollected 1 item                                                                                                                      
test_data.py::test_kolmogorov_smirnov [31mERROR
=============================================================== ERRORS ================================================================
[31m[1m______________________________________________ ERROR at setup of test_kolmogorov_smirnov ______________________________________________
request = <SubRequest 'ks_alpha' for <Function test_kolmogorov_smirnov>>
    @pytest.fixture(scope='session')
    def ks_alpha(request):
        # COMPLETE HERE: read the option ks_alpha from the command line,
        # and return it as a float
>       ks_alpha_threshold = request.config.option.input_artifact(ks_alpha)
[31m[1mE       AttributeError: 'Namespace' object has no attribute 'input_artifact'. Did you mean: 'sample_artifact'?
[31m[1mconftest.py[39m[22m:43: AttributeError
[33m========================================================== warnings summary ===========================================================
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.
<frozen importlib._bootstrap>:488
  <frozen importlib._bootstrap>:488: DeprecationWarning: Type google._upb._message.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.
../../../../../../../../../../opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/wandb/analytics/sentry.py:90
  /opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/wandb/analytics/sentry.py:90: SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
    self.hub = sentry_sdk.Hub(client)
../../../../../../../../../../opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:174
../../../../../../../../../../opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:174
../../../../../../../../../../opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:174
../../../../../../../../../../opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:174
test_data.py::test_kolmogorov_smirnov
test_data.py::test_kolmogorov_smirnov
test_data.py::test_kolmogorov_smirnov
  /opt/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/lib/python3.12/site-packages/google/protobuf/internal/well_known_types.py:174: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    self.FromDatetime(datetime.datetime.utcnow())
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[36m[1m======================================================= short test summary info =======================================================
[31mERROR[39m test_data.py::[1mtest_kolmogorov_smirnov[22m - AttributeError: 'Namespace' object has no attribute 'input_artifact'. Did you mean: 'sample_artifact'?
[31m==================================================== [33m10 warnings[39m, [31m[1m1 error[22m in 2.03s ====================================================